### PR TITLE
Test script cleanups

### PR DESCRIPTION
**Pull request by rhansen**
Here are a bunch of commits to fix and clean up some minor issues in the `tools/*.sh` scripts.

### CODE REVIEW

**Comment by gpocentek** [comment]
Thanks @rhansen !

This PR looks good but it changes the behavior of `build_test_env.sh`. I use this script to set up a dev environment. With your changes the environment is destroyed right after it's been created if you execute the script. Could you avoid calling the `cleanup` function if the script is executed directly?

**Comment by gpocentek** [comment]
I'm also getting an error on the file creation test.

**Comment by rhansen** [comment]
> This PR looks good but it changes the behavior of `build_test_env.sh`. I use this script to set up a dev environment. With your changes the environment is destroyed right after it's been created if you execute the script.

Ah, apologies—I didn't realize that script was used that way.  I thought it was just a shared library of sorts.

> Could you avoid calling the `cleanup` function if the script is executed directly?

Yes, I'll fix it soon.

> I'm also getting an error on the file creation test.

Can you paste the error message?

I did see random nginx "502 bad gateway" failures when testing this branch.  Those don't always happen, and they currently happen on master, so I don't believe any of the commits on this branch made anything worse.  I may be wrong.

**Comment by gpocentek** [comment]
On 2016-01-24 17:28, Richard Hansen wrote:
>> This PR looks good but it changes the behavior of build_test_env.sh.
>> I use this script to set up a dev environment. With your changes the
>> environment is destroyed right after it's been created if you
>> execute the script.
> 
> Ah, apologies—I didn't realize that script was used that way. I
> thought it was just a shared library of sorts.
> 
>> Could you avoid calling the cleanup function if the script is
>> executed directly?
> 
> Yes, I'll fix it soon.

Thanks.

>> I'm also getting an error on the file creation test.
> 
> Can you paste the error message?
> 
> I did see random nginx "502 bad gateway" failures when testing this
> branch. Those don't always happen, and they currently happen on
> master, so I don't believe any of the commits on this branch made
> anything worse. I may be wrong.

I couldn't reproduce exactly this error, but I've also seen those 502 
failures after an upgrade to 8.4.0. I agree this doesn't seem related to 
your patch.

Thank you!

**Comment by rhansen** [comment]
I made a few changes and rebased:

  * when run on its own, `build_test_env.sh` no longer runs `cleanup()` on exit (this preserves the behavior it has on `master`)
  * use the gentler `docker stop` instead of the aggressive `docker kill`
  * wait for the docker container to stop before removing it
  * don't suppress docker's stderr
  * add more log messages
  * move the `sleep 20` to `build_test_env.sh`

**Comment by gpocentek** [comment]
Thank you!

**Comment by rhansen** [comment]
Thank you!

**Pull request merged**
