### PR TITLE
Time tracking

### PR DESCRIPTION
**Pull request by savenger**
This adds support for gitlabs time tracking feature #221

### CODE REVIEW

**Comment by GhostLyrics** [comment]
The automated build failed. Please fix :)

**Comment by gpocentek** [comment]
Thank you. Could you squash your commits in a single one? Thanks.

**Comment by GhostLyrics** [comment]
@gpocentek you can do that from the merge interface too https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by gpocentek** [comment]
Ah nice! Never used this before, thanks @GhostLyrics

**Comment by DmytroLitvinov** [comment]
@gpocentek Hi. Cool feature was added, but it not documented. http://python-gitlab.readthedocs.io/en/stable/gl_objects/issues.html. But as I see [here](https://github.com/gpocentek/python-gitlab/pull/222/files) you added documentation.

**Comment by gpocentek** [comment]
@DmytroLitvinov the documentation is available at http://python-gitlab.readthedocs.io/en/latest/gl_objects/issues.html (latest instead of stable). It will switch to stable once I release the version containing this change (soonish).

Thank you for checking!

**Comment by DmytroLitvinov** [comment]
@gpocentek Thanks)  :+1:

**Comment by DmytroLitvinov** [comment]
@gpocentek It will in version 0.20 of this library, right?

**Comment by savenger** [comment]
I just saw that the documentation was not committed correctly. Should I open a new issue or re-open the issue? Or just open a new pull request?

**Comment by DmytroLitvinov** [comment]
@savenger Is it work correctly? I have an error.
```
Traceback (most recent call last):
  File "gtest.py", line 24, in <module>
    issue.reset_time_spent()
  File "/home/dmytro/.virtualenvs/GetMyHours/src/python-gitlab/gitlab/objects.py", line 432, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by DmytroLitvinov** [comment]
Also it is replaced login of function:
https://github.com/gpocentek/python-gitlab/blob/master/gitlab/objects.py#L1584
and here https://github.com/gpocentek/python-gitlab/blob/master/gitlab/objects.py#L1597 in variable `url` .

**Comment by gpocentek** [comment]
@DmytroLitvinov yes it will be in 0.20. I'm not sure about the release date, waiting on a couple changes. It shouldn't be long though (end of week, or next week maybe).

**Pull request merged**
