### PR TITLE
Changelog: improve Changelog & convert to Markdown

### LINKED ISSUE #229: Improve changelog
I suggest the following improvements for the Changelog:

- [ ] add release dates to the release headers
- [ ] add .md file extension, so GitHub parses the file
- [ ] link to the diffs between the release tags, as in [seen on keep-a-changelog](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md)

I'll try to send a PR for this soonish.

### PR DESCRIPTION
**Pull request by GhostLyrics**
I hope that you like what I did to the Changelog and are not offended I chose not to use RST for this, but the comparison links didn't seem well suited for what I could find about RST's link syntax.

- rename to ChangeLog.markdown
- add release dates
- add comparison links

Fixes #229

### CODE REVIEW

**Comment by gpocentek** [comment]
Thank you, this is a great improvement! A few comments:

- Could you switch to RST? Everything else is RST, and it would allow us to add the changelog in the docs
- Could you also amend you commit to fix the pep8 issue? Make the short commit message shorter, and add information in the commit message body.

Thanks!

**Comment by GhostLyrics** [comment]
Can you use variables for links in Rest like I used for the changes? See the bottom of the file. All this would need to be inline unless I overlooked something.

**Comment by gpocentek** [comment]
Yes, you can use something like:

`````
Version 0.19_:
 * blah blah blah
.. _0.19: http://whatever.com
`````

http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

**Comment by GhostLyrics** [comment]
Will try to do this today.

**Comment by GhostLyrics** [comment]
It's done and the tests pass :)

**Comment by gpocentek** [comment]
Looks good, thank you!

**Pull request merged**
